### PR TITLE
Probably don't want it to look like a spec.

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by tobie** [comment]
The WG's still up as to whether this will be turned into a W3C note or the introduction of the motion-sensor spec. In the meantime it makes sense to keep this as an ED.

**Comment by marcoscaceres** [comment]
Generally, W3C ED comes after FPWD, no? That is, it's unofficial until officially published.

**Comment by marcoscaceres** [comment]
Actually, I don't mind either way. Just want to see this move forward! Go team!! GO! :D

**Comment by tobie** [comment]
Yeah, this was approved by the WG on the call yesterday, so I think we're good process-wise. We also don't want to do a FPWD at this point because we don't know yet whether this will have normative content or not and don't want to trigger IP commitments until that's clarified.

**Pull request closed without merging**
